//! # Proxy-Complex — one capability, erased transaction
//!
//! [`OrderComplex::place`] depends on a **single** capability trait —
//! `OrderRepoProxy` — generated by `#[drive]` from the merged `run(...)` and
//! `step(...)` operation lists. The complex body never learns whether an
//! operation executes transactionally or not, nor how many repositories back
//! the capability.
//!
//! ```text
//! customer repo  ─┐
//! inventory repo ─┼── run_proxy! ─────────────┐
//! order repo     ─┘                            ├── OrderComplex::place<P: OrderRepoProxy>
//! customer repo  ─┐                            │
//! inventory repo ─┼── step_proxy! + one &mut Cx┘
//! order repo     ─┘
//! ```
//!
//! The same business logic runs against either wiring; the trait cannot tell
//! them apart. `P` is monomorphized at compile time, so the abstraction
//! introduces no dynamic dispatch.

use poprako_orchestra::OperProxy as _;
use poprako_orchestra::{Context, Level, Oper, Run, Step, drive};

pub struct Linearizable;

impl Level for Linearizable {}

pub struct Cx {
    pub events: Vec<String>,
}

impl Context for Cx {
    type Level = Linearizable;
}

#[derive(Oper)]
#[oper(output = ())]
pub struct EnsureCustomer<'a> {
    pub customer_id: &'a str,
}

#[derive(Oper)]
#[oper(output = ())]
pub struct ReserveStock<'a> {
    pub sku: &'a str,
    pub quantity: u32,
}

#[derive(Oper)]
#[oper(output = u64)]
pub struct CreateOrder<'a> {
    pub customer_id: &'a str,
    pub sku: &'a str,
    pub quantity: u32,
}

// One capability trait merges both operation lists. It carries no context,
// no level, and no run/step distinction: the transaction model is erased.
#[drive(
    context = Cx,
    error = String,
    proxy = OrderRepoProxy,
    run(
        for<'a> EnsureCustomer<'a>,
        for<'a> ReserveStock<'a>,
        for<'a> CreateOrder<'a>,
    ),
    step(
        for<'a> EnsureCustomer<'a>,
        for<'a> ReserveStock<'a>,
        for<'a> CreateOrder<'a>,
    ),
)]
pub trait OrderRepo {}

/// A logical atomic operation. It names the proxy capability — nothing else.
pub struct OrderComplex;

impl OrderComplex {
    pub async fn place<P>(
        proxy: &mut P,
        customer_id: &str,
        sku: &str,
        quantity: u32,
    ) -> Result<u64, String>
    where
        P: OrderRepoProxy,
    {
        EnsureCustomer { customer_id }.proxy_on(proxy).await?;

        ReserveStock { sku, quantity }.proxy_on(proxy).await?;

        CreateOrder {
            customer_id,
            sku,
            quantity,
        }
        .proxy_on(proxy)
        .await
    }
}

pub struct CustomerRepo;

impl Run<EnsureCustomer<'_>> for CustomerRepo {
    type Error = String;

    async fn run(&self, oper: &EnsureCustomer<'_>) -> Result<(), Self::Error> {
        if oper.customer_id.is_empty() {
            return Err("customer ID must not be empty".to_owned());
        }

        Ok(())
    }
}

impl Step<EnsureCustomer<'_>, Cx> for CustomerRepo {
    type Level = Linearizable;
    type Error = String;

    async fn step(
        &self,
        context: &mut Cx,
        oper: &EnsureCustomer<'_>,
    ) -> Result<(), Self::Error> {
        context
            .events
            .push(format!("ensure customer {}", oper.customer_id));

        Ok(())
    }
}

pub struct InventoryRepo;

impl Run<ReserveStock<'_>> for InventoryRepo {
    type Error = String;

    async fn run(&self, oper: &ReserveStock<'_>) -> Result<(), Self::Error> {
        if oper.quantity == 0 {
            return Err("quantity must be positive".to_owned());
        }

        Ok(())
    }
}

impl Step<ReserveStock<'_>, Cx> for InventoryRepo {
    type Level = Linearizable;
    type Error = String;

    async fn step(
        &self,
        context: &mut Cx,
        oper: &ReserveStock<'_>,
    ) -> Result<(), Self::Error> {
        context
            .events
            .push(format!("reserve {} x{}", oper.sku, oper.quantity));
        Ok(())
    }
}

pub struct OrderRepoImpl;

impl Run<CreateOrder<'_>> for OrderRepoImpl {
    type Error = String;

    async fn run(&self, oper: &CreateOrder<'_>) -> Result<u64, Self::Error> {
        Ok((oper.customer_id.len() + oper.sku.len() + oper.quantity as usize) as u64)
    }
}

impl Step<CreateOrder<'_>, Cx> for OrderRepoImpl {
    type Level = Linearizable;
    type Error = String;

    async fn step(
        &self,
        context: &mut Cx,
        oper: &CreateOrder<'_>,
    ) -> Result<u64, Self::Error> {
        context.events.push(format!(
            "create order for {}: {} x{}",
            oper.customer_id, oper.sku, oper.quantity,
        ));
        Ok(1)
    }
}

/// Run wiring: three repositories composed into one `OrderRepoProxy` value.
async fn place_via_run<CR, IR, OR>(
    customer_repo: &CR,
    inventory_repo: &IR,
    order_repo: &OR,
    customer_id: &str,
    sku: &str,
    quantity: u32,
) -> Result<u64, String>
where
    CR: for<'a> Run<EnsureCustomer<'a>, Error = String>,
    IR: for<'a> Run<ReserveStock<'a>, Error = String>,
    OR: for<'a> Run<CreateOrder<'a>, Error = String>,
{
    let mut proxy = poprako_orchestra::run_proxy! {
        customer_repo => for<'a> EnsureCustomer<'a>;
        inventory_repo => for<'a> ReserveStock<'a>;
        order_repo => for<'a> CreateOrder<'a>;
    };

    OrderComplex::place(&mut proxy, customer_id, sku, quantity).await
}

/// Step wiring: the same three repositories, one shared transaction context.
/// `StepProxy` owns `&mut Cx` once; each `exec` reborrows it for one step.
async fn place_via_step<CR, IR, OR>(
    context: &mut Cx,
    customer_repo: &CR,
    inventory_repo: &IR,
    order_repo: &OR,
    customer_id: &str,
    sku: &str,
    quantity: u32,
) -> Result<u64, String>
where
    CR: for<'a> Step<EnsureCustomer<'a>, Cx, Level = Linearizable, Error = String>,
    IR: for<'a> Step<ReserveStock<'a>, Cx, Level = Linearizable, Error = String>,
    OR: for<'a> Step<CreateOrder<'a>, Cx, Level = Linearizable, Error = String>,
{
    let mut proxy = poprako_orchestra::step_proxy! {
        context;
        customer_repo => for<'a> EnsureCustomer<'a>;
        inventory_repo => for<'a> ReserveStock<'a>;
        order_repo => for<'a> CreateOrder<'a>;
    };

    OrderComplex::place(&mut proxy, customer_id, sku, quantity).await
}

fn main() {
    futures::executor::block_on(async {
        // The same complex body runs against the non-transactional wiring...
        let order_id =
            place_via_run(&CustomerRepo, &InventoryRepo, &OrderRepoImpl, "c1", "sku-a", 2)
                .await
                .expect("run wiring should place the order");
        println!("run wiring placed order {order_id}");

        // ...and against the transactional wiring. `OrderComplex` cannot tell.
        let mut context = Cx { events: Vec::new() };
        let order_id =
            place_via_step(&mut context, &CustomerRepo, &InventoryRepo, &OrderRepoImpl, "c1", "sku-b", 3)
                .await
                .expect("step wiring should place the order");
        println!("step wiring placed order {order_id}");

        println!("events: {:?}", context.events);
        assert_eq!(context.events.len(), 3, "each step should record one event");
    });
}
