//! Defines the [`Nucl`] trait — the transactional nucleus that provides a
//! managed execution context and discriminates between backend-level and
//! step-level errors.
//!
//! A *nucleus* is the central coordinator of a transaction.  It supplies a
//! [`Context`](Nucl::Context) — typically a database connection, session, or
//! saga state — and exposes [`coord`](Nucl::coord) to run application logic
//! inside that context.  The implementor decides when to begin, commit, or
//! roll back the underlying transaction.
//!
//! # Error discrimination
//!
//! The associated [`Error`] enum separates failures that originate from the
//! backend (e.g. connection lost, deadlock detected) from failures that
//! originate from the step's own execution logic (e.g. validation failure,
//! business-rule violation).  This lets callers handle the two categories
//! differently — for instance, retrying on backend errors without re-running
//! side-effectful step logic.

use async_trait::async_trait;
use std::result::Result as StdResult;

use crate::util::AsyncFunc;

/// A discriminated error that separates backend failures from step-execution
/// failures.
///
/// - [`Backend`](Error::Backend) — failures originating from the
///   transactional backend (database, message broker, etc.).
/// - [`Exec`](Error::Exec) — failures originating from within the step or
///   application logic being coordinated.
pub enum Error<E, XE> {
    /// An error occurred in the underlying transactional backend.
    Backend(E),
    /// An error occurred during step-execution.
    Exec(XE),
}

/// Shorthand for `Result<T, Error<E, XE>>`.
pub type Result<T, E, XE> = StdResult<T, Error<E, XE>>;

/// A transactional nucleus that provides a managed [`Context`] and coordinates
/// the execution of application logic inside it.
///
/// # Type parameters
///
/// * [`Context`](Nucl::Context) — the environment provided by the backend
///   (e.g. a database transaction handle).  Each call to
///   [`coord`](Nucl::coord) receives a fresh `&mut Context` for the duration
///   of the closure.
///
/// # How it works
///
/// 1. The implementor acquires or creates a [`Context`](Nucl::Context)
///    (beginning a transaction if applicable).
/// 2. The caller-supplied async closure `f` receives `&mut Context` and runs
///    its step logic.
/// 3. The implementor commits the transaction on success or rolls it back on
///    error, mapping its own internal error into
///    [`Error::Backend`](Error::Backend) and passing through the closure's
///    error as [`Error::Exec`](Error::Exec).
///
/// # Higher-ranked async closure bounds
///
/// The bound `for<'c> F: AsyncFnOnce(&'c mut Self::Context) -> StdResult<T,
/// E>` requires that the closure accept a reference with *any* lifetime
/// `'c`.  Because stable Rust cannot express this constraint solely with
/// `AsyncFnOnce`, the bound also requires the legacy [`FnOnce`] equivalent
/// via [`AsyncFunc`].  See [`AsyncFunc`](crate::util::AsyncFunc) for details.
#[async_trait]
pub trait Nucl {
    /// Error type generated by the backend (database, broker, etc.).
    type Error;

    /// Context type that the nucleus provisions for each
    /// [`coord`](Nucl::coord) call, typically wrapping a backend session or
    /// transaction handle.
    type Context;

    /// Run an async computation inside the nucleus's managed context.
    ///
    /// The closure `f` receives `&mut Self::Context` and returns either
    /// `Ok(T)` on success or `Err(E)` on a step-level failure.  Backend
    /// errors are captured as [`Error::Backend`](Error::Backend).
    async fn coord<F, T, E>(&self, f: F) -> Result<T, Self::Error, E>
    where
        for<'c> F: AsyncFnOnce(&'c mut Self::Context) -> StdResult<T, E>
            + AsyncFunc<&'c mut Self::Context, StdResult<T, E>, Fut: Send>
            + Send;
}
