use crate::Oper;

/// Executes an [`Oper`] through a repository-backed proxy.
///
/// Implementations generated by [`proxy!`](crate::proxy!) select one declared
/// run or step provider for each operation at compile time.
pub trait Proxy<O>
where
    O: Oper,
{
    /// Error returned when the proxied operation cannot be executed.
    type Error;

    /// Executes `oper` through the selected provider.
    fn exec(&mut self, oper: &O) -> impl Future<Output = Result<O::Output, Self::Error>> + Send;
}

/// An [`Oper`] extension trait that executes an operation through a [`Proxy`].
#[cfg(feature = "oper_ext")]
pub trait OperProxy: Oper {
    /// Executes this operation with `proxy`.
    fn proxy_on<'a, P>(
        &'a self,
        proxy: &'a mut P,
    ) -> impl Future<Output = Result<Self::Output, <P as Proxy<Self>>::Error>> + Send + 'a
    where
        Self: Sized,
        P: Proxy<Self> + ?Sized,
    {
        proxy.exec(self)
    }
}

#[cfg(feature = "oper_ext")]
impl<O> OperProxy for O where O: Oper {}
